### ISSUE TITLE
Vercel 部署 (MongoDB)多次失败，且都在building一步失败

### ISSUE THREAD

**Issue by kiwylai** [Qexo/Qexo#324]
### Qexo 版本

v.2.4.3

### 平台

Vercel & MongoDB

### 问题描述

试了几个仓库名，但是都在building一步就失败了。请指教，谢谢！

### 截图

![image](https://user-images.githubusercontent.com/76679115/226394545-e1bacc21-1662-41a7-899e-d4fe3314a994.png)

**Comment by Fgaoxing** [comment]
报错之后退出，然后选择对应项目，配置环境变量即可



在 2023-03-20 23:54:26，"kiwylai" ***@***.***> 写道：

Qexo 版本

v.2.4.3

平台

Vercel & MongoDB

问题描述

试了几个仓库名，但是都在building一步就失败了。请指教，谢谢！

复现链接

No response

截图

**Comment by Refeain** [comment]
我也是
![image](https://user-images.githubusercontent.com/101313620/226574418-6a419567-7f1a-437a-964f-291d29619cb3.png)

**Comment by kiwylai** [comment]
请问我在mongoDB完成图片所示，下一步应该怎么操作啊？小白实在看不懂
https://www.oplog.cn/qexo/configs/provider.html 网页所说。谢谢！[image: image.png]

crsn ***@***.***> 于2023年3月20日周一 17:32写道：

**Comment by am-abudu** [comment]
请按照[文档](https://www.oplog.cn/qexo)正确部署环境变量后重试

**Comment by MartinLiuMingZhi** [comment]
<html>
<body>



WARN! Due to `builds` existing in your configuration file, the Build and Development Settings defined in your Project Settings will not apply. Learn More: https://vercel.link/unused-build-settings
20:25:17.194 | ./migrate.sh: line 1: pip: command not found
20:25:17.223 | Traceback (most recent call last):
20:25:17.223 | File "/vercel/path0/manage.py", line 11, in main
20:25:17.224 | from django.core.management import execute_from_command_line
20:25:17.224 | ModuleNotFoundError: No module named 'django'
20:25:17.224 |  
20:25:17.224 | The above exception was the direct cause of the following exception:
20:25:17.224 |  
20:25:17.224 | Traceback (most recent call last):
20:25:17.224 | File "/vercel/path0/manage.py", line 22, in <module>
20:25:17.224 | main()
20:25:17.224 | File "/vercel/path0/manage.py", line 13, in main
20:25:17.224 | raise ImportError(
20:25:17.225 | ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
20:25:17.235 | Traceback (most recent call last):
20:25:17.235 | File "/vercel/path0/manage.py", line 11, in main
20:25:17.236 | from django.core.management import execute_from_command_line
20:25:17.236 | ModuleNotFoundError: No module named 'django'
20:25:17.236

<br class="Apple-interchange-newline">
</body>
</html>在vercel部署的时候我已经按照要求配置了环境变量，但是building时显示没有python环境报错好像是
